### PR TITLE
Jellybean

### PR DESCRIPTION
**Pull request by playfulgod**
fixed build issue for builder.clockworkmod.com

### CODE REVIEW

**Comment by eljef** [comment]
All change requests need to be pushed through Gerrit.

**Comment by cm-gerrit** [comment]
Hi there;

This is an automated reply, to let you know CyanogenMod doesn't merge pull
requests submitted directly to our github.com repositories.

You can submit your change requests through our public review system,
located at http://review.cyanogenmod.com/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, we also suggest you take
a look at http://wiki.cyanogenmod.com/wiki/Howto:_Gerrit

Thanks!

**Comment by Shabbypenguin** [comment]
gerrit claims project doesnt exist

**Comment by koush** [comment]
I guess @jeagoss hadn't forked it yet, so I just accepted the merge until he does that.

**Comment by playfulgod** [comment]
thank you ;)

**Comment by eljef** [comment]
Actually, the project did exist. So now this repo is ahead of gerrit. I need to manually fix this.

**Comment by playfulgod** [comment]
Sorry I must have been doing something wrong then. I am a gerrit n00b :(

I was trying to follow the wiki.

**Comment by eljef** [comment]
No probs.  All fixed up.

**Pull request merged**
